### ISSUE TITLE
Need to check file CRC or something to see if existing files need updating

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/VS_Mac_Meadow_Extension#1]
Right now we're not checking the CRCs on the existing files to see if they need updating. so for instance, if I make a change to `Meadow.Core.dll`, and re-deploy, it doesn't actually redeploy the file, i have to manually call `--DeleteFile -FileName Meadow.Core.dll` from the CLI.

**Comment by adrianstevens** [comment]
This is done - closing issue
