### ISSUE TITLE
Meadow device not displaying in VS4Mac v.17.4, extension install with warnings

### ISSUE THREAD

**Issue by markanator** [WildernessLabs/VS_Mac_Meadow_Extension#36]
I've followed the docs instructions to get started on a new device and I am unable to deploy the Hello Meadow example app to the device.
- I've provisioned the Meadow device (downloaded and flashed the device)
- I am on a M1 MacPro running Ventura 13.0 MacOS. 
- VS4Mac was recently updated to v17.4 (build 2406), I have both arm + x64 versions of .net 6 installed.
- I am running Meadow CLI v.0.90.0 and the latest version of Meadow OS on the device.
- I am able to get device information from the terminal using the CLI but VS4Mac does not give me the appropriate deploy target.

I've noticed that the Extension for Meadow within VS4Mac shows an error when installing:
<img width="815" alt="Screenshot 2022-11-13 at 2 38 41 PM" src="https://user-images.githubusercontent.com/16071902/201547016-f32b4d56-ea08-48e6-984b-4a29d3f84755.png">

I am not able to install an earlier version of VS4Mac at this time.

(Snippet of VS4Mac displaying default target not Meadow Device)
<img width="615" alt="Screenshot 2022-11-13 at 3 14 03 PM" src="https://user-images.githubusercontent.com/16071902/201547195-dd0eb0a1-74df-4d3e-8d92-5a77a3a7a54a.png">

Any help or guidance?

**Comment by mchristensen80** [comment]
@markanator I received similar warnings when I tried to install the extension using the built-in VS 2022 for Mac Microsoft extension repository. Have you tried downloading the release (mpack file) directly from GitHub? After uninstalling the extension version you are referring to, I downloaded an mpack file from the Github releases page. I installed the extension from file : [VS Mac VS2022 Extension (v0.90.01) for Meadow 0.9.0.2 - RC1](https://github.com/WildernessLabs/VS_Mac_Meadow_Extension/releases/tag/v0.90.01.VS2022), and it worked for me.
